# docker-compose.yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached # ホストのプロジェクトルートをコンテナの/workspaceにマウント
    # command: sleep infinity # コンテナを起動し続けるため (開発中はこれでOK)
    # アプリ実行コマンドは後で調整
    ports:
      - "8080:8080" # Goアプリ用
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=gouser
      - DB_PASSWORD=gopassword
      - DB_NAME=login_db
      - GIN_MODE=debug # Ginフレームワークを使用する場合

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: gopassword
      POSTGRES_DB: login_db
    ports:
      - "5434:5432" # ホストからDBにアクセスする場合（任意）

volumes:
  postgres_data: # DBデータ永続化用